// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Correlation is the predicate function for correlation builders.
type Correlation func(*sql.Selector)

// Dataset is the predicate function for dataset builders.
type Dataset func(*sql.Selector)

// DatasetParams is the predicate function for datasetparams builders.
type DatasetParams func(*sql.Selector)

// Dictionary is the predicate function for dictionary builders.
type Dictionary func(*sql.Selector)

// DictionaryEntry is the predicate function for dictionaryentry builders.
type DictionaryEntry func(*sql.Selector)

// Indicator is the predicate function for indicator builders.
type Indicator func(*sql.Selector)

// IndicatorValueAlias is the predicate function for indicatorvaluealias builders.
type IndicatorValueAlias func(*sql.Selector)

// Observation is the predicate function for observation builders.
type Observation func(*sql.Selector)

// Scale is the predicate function for scale builders.
type Scale func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserSettings is the predicate function for usersettings builders.
type UserSettings func(*sql.Selector)
