version: '3.7'

services:
  correlateme_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: test
      POSTGRES_DB: correlateme
    ports:
      - "5442:5432"