// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/datasetstyle"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/predicate"
)

// DatasetStyleDelete is the builder for deleting a DatasetStyle entity.
type DatasetStyleDelete struct {
	config
	hooks    []Hook
	mutation *DatasetStyleMutation
}

// Where adds a new predicate to the DatasetStyleDelete builder.
func (dsd *DatasetStyleDelete) Where(ps ...predicate.DatasetStyle) *DatasetStyleDelete {
	dsd.mutation.predicates = append(dsd.mutation.predicates, ps...)
	return dsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dsd *DatasetStyleDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(dsd.hooks) == 0 {
		affected, err = dsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DatasetStyleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dsd.mutation = mutation
			affected, err = dsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dsd.hooks) - 1; i >= 0; i-- {
			mut = dsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (dsd *DatasetStyleDelete) ExecX(ctx context.Context) int {
	n, err := dsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dsd *DatasetStyleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: datasetstyle.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: datasetstyle.FieldID,
			},
		},
	}
	if ps := dsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, dsd.driver, _spec)
}

// DatasetStyleDeleteOne is the builder for deleting a single DatasetStyle entity.
type DatasetStyleDeleteOne struct {
	dsd *DatasetStyleDelete
}

// Exec executes the deletion query.
func (dsdo *DatasetStyleDeleteOne) Exec(ctx context.Context) error {
	n, err := dsdo.dsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{datasetstyle.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dsdo *DatasetStyleDeleteOne) ExecX(ctx context.Context) {
	dsdo.dsd.ExecX(ctx)
}
