// Code generated by entc, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/DanielTitkov/correlateme-server/internal/domain"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/dataset"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/datasetparams"
)

// DatasetParams is the model entity for the DatasetParams schema.
type DatasetParams struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Style holds the value of the "style" field.
	Style domain.DatasetStyle `json:"style,omitempty"`
	// Aggregation holds the value of the "aggregation" field.
	Aggregation domain.DatasetAggregation `json:"aggregation,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DatasetParamsQuery when eager-loading is set.
	Edges                  DatasetParamsEdges `json:"edges"`
	dataset_dataset_params *int
}

// DatasetParamsEdges holds the relations/edges for other nodes in the graph.
type DatasetParamsEdges struct {
	// Dataset holds the value of the dataset edge.
	Dataset *Dataset `json:"dataset,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DatasetOrErr returns the Dataset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DatasetParamsEdges) DatasetOrErr() (*Dataset, error) {
	if e.loadedTypes[0] {
		if e.Dataset == nil {
			// The edge dataset was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: dataset.Label}
		}
		return e.Dataset, nil
	}
	return nil, &NotLoadedError{edge: "dataset"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DatasetParams) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case datasetparams.FieldStyle, datasetparams.FieldAggregation:
			values[i] = &[]byte{}
		case datasetparams.FieldID:
			values[i] = &sql.NullInt64{}
		case datasetparams.ForeignKeys[0]: // dataset_dataset_params
			values[i] = &sql.NullInt64{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type DatasetParams", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DatasetParams fields.
func (dp *DatasetParams) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case datasetparams.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			dp.ID = int(value.Int64)
		case datasetparams.FieldStyle:

			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field style", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &dp.Style); err != nil {
					return fmt.Errorf("unmarshal field style: %v", err)
				}
			}
		case datasetparams.FieldAggregation:

			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field aggregation", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &dp.Aggregation); err != nil {
					return fmt.Errorf("unmarshal field aggregation: %v", err)
				}
			}
		case datasetparams.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field dataset_dataset_params", value)
			} else if value.Valid {
				dp.dataset_dataset_params = new(int)
				*dp.dataset_dataset_params = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryDataset queries the "dataset" edge of the DatasetParams entity.
func (dp *DatasetParams) QueryDataset() *DatasetQuery {
	return (&DatasetParamsClient{config: dp.config}).QueryDataset(dp)
}

// Update returns a builder for updating this DatasetParams.
// Note that you need to call DatasetParams.Unwrap() before calling this method if this DatasetParams
// was returned from a transaction, and the transaction was committed or rolled back.
func (dp *DatasetParams) Update() *DatasetParamsUpdateOne {
	return (&DatasetParamsClient{config: dp.config}).UpdateOne(dp)
}

// Unwrap unwraps the DatasetParams entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dp *DatasetParams) Unwrap() *DatasetParams {
	tx, ok := dp.config.driver.(*txDriver)
	if !ok {
		panic("ent: DatasetParams is not a transactional entity")
	}
	dp.config.driver = tx.drv
	return dp
}

// String implements the fmt.Stringer.
func (dp *DatasetParams) String() string {
	var builder strings.Builder
	builder.WriteString("DatasetParams(")
	builder.WriteString(fmt.Sprintf("id=%v", dp.ID))
	builder.WriteString(", style=")
	builder.WriteString(fmt.Sprintf("%v", dp.Style))
	builder.WriteString(", aggregation=")
	builder.WriteString(fmt.Sprintf("%v", dp.Aggregation))
	builder.WriteByte(')')
	return builder.String()
}

// DatasetParamsSlice is a parsable slice of DatasetParams.
type DatasetParamsSlice []*DatasetParams

func (dp DatasetParamsSlice) config(cfg config) {
	for _i := range dp {
		dp[_i].config = cfg
	}
}
