// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DanielTitkov/correlateme-server/internal/domain"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/dataset"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/datasetstyle"
)

// DatasetStyleCreate is the builder for creating a DatasetStyle entity.
type DatasetStyleCreate struct {
	config
	mutation *DatasetStyleMutation
	hooks    []Hook
}

// SetStyle sets the "style" field.
func (dsc *DatasetStyleCreate) SetStyle(ds domain.DatasetStyle) *DatasetStyleCreate {
	dsc.mutation.SetStyle(ds)
	return dsc
}

// SetDatasetID sets the "dataset" edge to the Dataset entity by ID.
func (dsc *DatasetStyleCreate) SetDatasetID(id int) *DatasetStyleCreate {
	dsc.mutation.SetDatasetID(id)
	return dsc
}

// SetDataset sets the "dataset" edge to the Dataset entity.
func (dsc *DatasetStyleCreate) SetDataset(d *Dataset) *DatasetStyleCreate {
	return dsc.SetDatasetID(d.ID)
}

// Mutation returns the DatasetStyleMutation object of the builder.
func (dsc *DatasetStyleCreate) Mutation() *DatasetStyleMutation {
	return dsc.mutation
}

// Save creates the DatasetStyle in the database.
func (dsc *DatasetStyleCreate) Save(ctx context.Context) (*DatasetStyle, error) {
	var (
		err  error
		node *DatasetStyle
	)
	if len(dsc.hooks) == 0 {
		if err = dsc.check(); err != nil {
			return nil, err
		}
		node, err = dsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DatasetStyleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = dsc.check(); err != nil {
				return nil, err
			}
			dsc.mutation = mutation
			node, err = dsc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dsc.hooks) - 1; i >= 0; i-- {
			mut = dsc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dsc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dsc *DatasetStyleCreate) SaveX(ctx context.Context) *DatasetStyle {
	v, err := dsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (dsc *DatasetStyleCreate) check() error {
	if _, ok := dsc.mutation.Style(); !ok {
		return &ValidationError{Name: "style", err: errors.New("ent: missing required field \"style\"")}
	}
	if _, ok := dsc.mutation.DatasetID(); !ok {
		return &ValidationError{Name: "dataset", err: errors.New("ent: missing required edge \"dataset\"")}
	}
	return nil
}

func (dsc *DatasetStyleCreate) sqlSave(ctx context.Context) (*DatasetStyle, error) {
	_node, _spec := dsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dsc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (dsc *DatasetStyleCreate) createSpec() (*DatasetStyle, *sqlgraph.CreateSpec) {
	var (
		_node = &DatasetStyle{config: dsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: datasetstyle.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: datasetstyle.FieldID,
			},
		}
	)
	if value, ok := dsc.mutation.Style(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: datasetstyle.FieldStyle,
		})
		_node.Style = value
	}
	if nodes := dsc.mutation.DatasetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   datasetstyle.DatasetTable,
			Columns: []string{datasetstyle.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: dataset.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DatasetStyleCreateBulk is the builder for creating many DatasetStyle entities in bulk.
type DatasetStyleCreateBulk struct {
	config
	builders []*DatasetStyleCreate
}

// Save creates the DatasetStyle entities in the database.
func (dscb *DatasetStyleCreateBulk) Save(ctx context.Context) ([]*DatasetStyle, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dscb.builders))
	nodes := make([]*DatasetStyle, len(dscb.builders))
	mutators := make([]Mutator, len(dscb.builders))
	for i := range dscb.builders {
		func(i int, root context.Context) {
			builder := dscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DatasetStyleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dscb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dscb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dscb *DatasetStyleCreateBulk) SaveX(ctx context.Context) []*DatasetStyle {
	v, err := dscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
