// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/detectionjob"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/predicate"
)

// DetectionJobDelete is the builder for deleting a DetectionJob entity.
type DetectionJobDelete struct {
	config
	hooks    []Hook
	mutation *DetectionJobMutation
}

// Where adds a new predicate to the DetectionJobDelete builder.
func (djd *DetectionJobDelete) Where(ps ...predicate.DetectionJob) *DetectionJobDelete {
	djd.mutation.predicates = append(djd.mutation.predicates, ps...)
	return djd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (djd *DetectionJobDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(djd.hooks) == 0 {
		affected, err = djd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DetectionJobMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			djd.mutation = mutation
			affected, err = djd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(djd.hooks) - 1; i >= 0; i-- {
			mut = djd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, djd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (djd *DetectionJobDelete) ExecX(ctx context.Context) int {
	n, err := djd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (djd *DetectionJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: detectionjob.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: detectionjob.FieldID,
			},
		},
	}
	if ps := djd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, djd.driver, _spec)
}

// DetectionJobDeleteOne is the builder for deleting a single DetectionJob entity.
type DetectionJobDeleteOne struct {
	djd *DetectionJobDelete
}

// Exec executes the deletion query.
func (djdo *DetectionJobDeleteOne) Exec(ctx context.Context) error {
	n, err := djdo.djd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{detectionjob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (djdo *DetectionJobDeleteOne) ExecX(ctx context.Context) {
	djdo.djd.ExecX(ctx)
}
