// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/detectionjobinstance"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/predicate"
)

// DetectionJobInstanceDelete is the builder for deleting a DetectionJobInstance entity.
type DetectionJobInstanceDelete struct {
	config
	hooks    []Hook
	mutation *DetectionJobInstanceMutation
}

// Where adds a new predicate to the DetectionJobInstanceDelete builder.
func (djid *DetectionJobInstanceDelete) Where(ps ...predicate.DetectionJobInstance) *DetectionJobInstanceDelete {
	djid.mutation.predicates = append(djid.mutation.predicates, ps...)
	return djid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (djid *DetectionJobInstanceDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(djid.hooks) == 0 {
		affected, err = djid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DetectionJobInstanceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			djid.mutation = mutation
			affected, err = djid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(djid.hooks) - 1; i >= 0; i-- {
			mut = djid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, djid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (djid *DetectionJobInstanceDelete) ExecX(ctx context.Context) int {
	n, err := djid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (djid *DetectionJobInstanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: detectionjobinstance.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: detectionjobinstance.FieldID,
			},
		},
	}
	if ps := djid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, djid.driver, _spec)
}

// DetectionJobInstanceDeleteOne is the builder for deleting a single DetectionJobInstance entity.
type DetectionJobInstanceDeleteOne struct {
	djid *DetectionJobInstanceDelete
}

// Exec executes the deletion query.
func (djido *DetectionJobInstanceDeleteOne) Exec(ctx context.Context) error {
	n, err := djido.djid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{detectionjobinstance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (djido *DetectionJobInstanceDeleteOne) ExecX(ctx context.Context) {
	djido.djid.ExecX(ctx)
}
