// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/dictionary"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/dictionaryentry"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/predicate"
)

// DictionaryEntryQuery is the builder for querying DictionaryEntry entities.
type DictionaryEntryQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.DictionaryEntry
	// eager-loading edges.
	withDictionary *DictionaryQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DictionaryEntryQuery builder.
func (deq *DictionaryEntryQuery) Where(ps ...predicate.DictionaryEntry) *DictionaryEntryQuery {
	deq.predicates = append(deq.predicates, ps...)
	return deq
}

// Limit adds a limit step to the query.
func (deq *DictionaryEntryQuery) Limit(limit int) *DictionaryEntryQuery {
	deq.limit = &limit
	return deq
}

// Offset adds an offset step to the query.
func (deq *DictionaryEntryQuery) Offset(offset int) *DictionaryEntryQuery {
	deq.offset = &offset
	return deq
}

// Order adds an order step to the query.
func (deq *DictionaryEntryQuery) Order(o ...OrderFunc) *DictionaryEntryQuery {
	deq.order = append(deq.order, o...)
	return deq
}

// QueryDictionary chains the current query on the "dictionary" edge.
func (deq *DictionaryEntryQuery) QueryDictionary() *DictionaryQuery {
	query := &DictionaryQuery{config: deq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := deq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := deq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dictionaryentry.Table, dictionaryentry.FieldID, selector),
			sqlgraph.To(dictionary.Table, dictionary.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dictionaryentry.DictionaryTable, dictionaryentry.DictionaryColumn),
		)
		fromU = sqlgraph.SetNeighbors(deq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DictionaryEntry entity from the query.
// Returns a *NotFoundError when no DictionaryEntry was found.
func (deq *DictionaryEntryQuery) First(ctx context.Context) (*DictionaryEntry, error) {
	nodes, err := deq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dictionaryentry.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (deq *DictionaryEntryQuery) FirstX(ctx context.Context) *DictionaryEntry {
	node, err := deq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DictionaryEntry ID from the query.
// Returns a *NotFoundError when no DictionaryEntry ID was found.
func (deq *DictionaryEntryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = deq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dictionaryentry.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (deq *DictionaryEntryQuery) FirstIDX(ctx context.Context) int {
	id, err := deq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DictionaryEntry entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one DictionaryEntry entity is not found.
// Returns a *NotFoundError when no DictionaryEntry entities are found.
func (deq *DictionaryEntryQuery) Only(ctx context.Context) (*DictionaryEntry, error) {
	nodes, err := deq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dictionaryentry.Label}
	default:
		return nil, &NotSingularError{dictionaryentry.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (deq *DictionaryEntryQuery) OnlyX(ctx context.Context) *DictionaryEntry {
	node, err := deq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DictionaryEntry ID in the query.
// Returns a *NotSingularError when exactly one DictionaryEntry ID is not found.
// Returns a *NotFoundError when no entities are found.
func (deq *DictionaryEntryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = deq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dictionaryentry.Label}
	default:
		err = &NotSingularError{dictionaryentry.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (deq *DictionaryEntryQuery) OnlyIDX(ctx context.Context) int {
	id, err := deq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DictionaryEntries.
func (deq *DictionaryEntryQuery) All(ctx context.Context) ([]*DictionaryEntry, error) {
	if err := deq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return deq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (deq *DictionaryEntryQuery) AllX(ctx context.Context) []*DictionaryEntry {
	nodes, err := deq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DictionaryEntry IDs.
func (deq *DictionaryEntryQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := deq.Select(dictionaryentry.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (deq *DictionaryEntryQuery) IDsX(ctx context.Context) []int {
	ids, err := deq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (deq *DictionaryEntryQuery) Count(ctx context.Context) (int, error) {
	if err := deq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return deq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (deq *DictionaryEntryQuery) CountX(ctx context.Context) int {
	count, err := deq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (deq *DictionaryEntryQuery) Exist(ctx context.Context) (bool, error) {
	if err := deq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return deq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (deq *DictionaryEntryQuery) ExistX(ctx context.Context) bool {
	exist, err := deq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DictionaryEntryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (deq *DictionaryEntryQuery) Clone() *DictionaryEntryQuery {
	if deq == nil {
		return nil
	}
	return &DictionaryEntryQuery{
		config:         deq.config,
		limit:          deq.limit,
		offset:         deq.offset,
		order:          append([]OrderFunc{}, deq.order...),
		predicates:     append([]predicate.DictionaryEntry{}, deq.predicates...),
		withDictionary: deq.withDictionary.Clone(),
		// clone intermediate query.
		sql:  deq.sql.Clone(),
		path: deq.path,
	}
}

// WithDictionary tells the query-builder to eager-load the nodes that are connected to
// the "dictionary" edge. The optional arguments are used to configure the query builder of the edge.
func (deq *DictionaryEntryQuery) WithDictionary(opts ...func(*DictionaryQuery)) *DictionaryEntryQuery {
	query := &DictionaryQuery{config: deq.config}
	for _, opt := range opts {
		opt(query)
	}
	deq.withDictionary = query
	return deq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DictionaryEntry.Query().
//		GroupBy(dictionaryentry.FieldCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (deq *DictionaryEntryQuery) GroupBy(field string, fields ...string) *DictionaryEntryGroupBy {
	group := &DictionaryEntryGroupBy{config: deq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := deq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return deq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//	}
//
//	client.DictionaryEntry.Query().
//		Select(dictionaryentry.FieldCode).
//		Scan(ctx, &v)
//
func (deq *DictionaryEntryQuery) Select(field string, fields ...string) *DictionaryEntrySelect {
	deq.fields = append([]string{field}, fields...)
	return &DictionaryEntrySelect{DictionaryEntryQuery: deq}
}

func (deq *DictionaryEntryQuery) prepareQuery(ctx context.Context) error {
	for _, f := range deq.fields {
		if !dictionaryentry.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if deq.path != nil {
		prev, err := deq.path(ctx)
		if err != nil {
			return err
		}
		deq.sql = prev
	}
	return nil
}

func (deq *DictionaryEntryQuery) sqlAll(ctx context.Context) ([]*DictionaryEntry, error) {
	var (
		nodes       = []*DictionaryEntry{}
		withFKs     = deq.withFKs
		_spec       = deq.querySpec()
		loadedTypes = [1]bool{
			deq.withDictionary != nil,
		}
	)
	if deq.withDictionary != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, dictionaryentry.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &DictionaryEntry{config: deq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, deq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := deq.withDictionary; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*DictionaryEntry)
		for i := range nodes {
			if fk := nodes[i].dictionary_entries; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(dictionary.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "dictionary_entries" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Dictionary = n
			}
		}
	}

	return nodes, nil
}

func (deq *DictionaryEntryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := deq.querySpec()
	return sqlgraph.CountNodes(ctx, deq.driver, _spec)
}

func (deq *DictionaryEntryQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := deq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (deq *DictionaryEntryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dictionaryentry.Table,
			Columns: dictionaryentry.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dictionaryentry.FieldID,
			},
		},
		From:   deq.sql,
		Unique: true,
	}
	if fields := deq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictionaryentry.FieldID)
		for i := range fields {
			if fields[i] != dictionaryentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := deq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := deq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := deq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := deq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, dictionaryentry.ValidColumn)
			}
		}
	}
	return _spec
}

func (deq *DictionaryEntryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(deq.driver.Dialect())
	t1 := builder.Table(dictionaryentry.Table)
	selector := builder.Select(t1.Columns(dictionaryentry.Columns...)...).From(t1)
	if deq.sql != nil {
		selector = deq.sql
		selector.Select(selector.Columns(dictionaryentry.Columns...)...)
	}
	for _, p := range deq.predicates {
		p(selector)
	}
	for _, p := range deq.order {
		p(selector, dictionaryentry.ValidColumn)
	}
	if offset := deq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := deq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DictionaryEntryGroupBy is the group-by builder for DictionaryEntry entities.
type DictionaryEntryGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (degb *DictionaryEntryGroupBy) Aggregate(fns ...AggregateFunc) *DictionaryEntryGroupBy {
	degb.fns = append(degb.fns, fns...)
	return degb
}

// Scan applies the group-by query and scans the result into the given value.
func (degb *DictionaryEntryGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := degb.path(ctx)
	if err != nil {
		return err
	}
	degb.sql = query
	return degb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (degb *DictionaryEntryGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := degb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (degb *DictionaryEntryGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(degb.fields) > 1 {
		return nil, errors.New("ent: DictionaryEntryGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := degb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (degb *DictionaryEntryGroupBy) StringsX(ctx context.Context) []string {
	v, err := degb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (degb *DictionaryEntryGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = degb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{dictionaryentry.Label}
	default:
		err = fmt.Errorf("ent: DictionaryEntryGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (degb *DictionaryEntryGroupBy) StringX(ctx context.Context) string {
	v, err := degb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (degb *DictionaryEntryGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(degb.fields) > 1 {
		return nil, errors.New("ent: DictionaryEntryGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := degb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (degb *DictionaryEntryGroupBy) IntsX(ctx context.Context) []int {
	v, err := degb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (degb *DictionaryEntryGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = degb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{dictionaryentry.Label}
	default:
		err = fmt.Errorf("ent: DictionaryEntryGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (degb *DictionaryEntryGroupBy) IntX(ctx context.Context) int {
	v, err := degb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (degb *DictionaryEntryGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(degb.fields) > 1 {
		return nil, errors.New("ent: DictionaryEntryGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := degb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (degb *DictionaryEntryGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := degb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (degb *DictionaryEntryGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = degb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{dictionaryentry.Label}
	default:
		err = fmt.Errorf("ent: DictionaryEntryGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (degb *DictionaryEntryGroupBy) Float64X(ctx context.Context) float64 {
	v, err := degb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (degb *DictionaryEntryGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(degb.fields) > 1 {
		return nil, errors.New("ent: DictionaryEntryGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := degb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (degb *DictionaryEntryGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := degb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (degb *DictionaryEntryGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = degb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{dictionaryentry.Label}
	default:
		err = fmt.Errorf("ent: DictionaryEntryGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (degb *DictionaryEntryGroupBy) BoolX(ctx context.Context) bool {
	v, err := degb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (degb *DictionaryEntryGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range degb.fields {
		if !dictionaryentry.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := degb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := degb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (degb *DictionaryEntryGroupBy) sqlQuery() *sql.Selector {
	selector := degb.sql
	columns := make([]string, 0, len(degb.fields)+len(degb.fns))
	columns = append(columns, degb.fields...)
	for _, fn := range degb.fns {
		columns = append(columns, fn(selector, dictionaryentry.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(degb.fields...)
}

// DictionaryEntrySelect is the builder for selecting fields of DictionaryEntry entities.
type DictionaryEntrySelect struct {
	*DictionaryEntryQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (des *DictionaryEntrySelect) Scan(ctx context.Context, v interface{}) error {
	if err := des.prepareQuery(ctx); err != nil {
		return err
	}
	des.sql = des.DictionaryEntryQuery.sqlQuery(ctx)
	return des.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (des *DictionaryEntrySelect) ScanX(ctx context.Context, v interface{}) {
	if err := des.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (des *DictionaryEntrySelect) Strings(ctx context.Context) ([]string, error) {
	if len(des.fields) > 1 {
		return nil, errors.New("ent: DictionaryEntrySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := des.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (des *DictionaryEntrySelect) StringsX(ctx context.Context) []string {
	v, err := des.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (des *DictionaryEntrySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = des.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{dictionaryentry.Label}
	default:
		err = fmt.Errorf("ent: DictionaryEntrySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (des *DictionaryEntrySelect) StringX(ctx context.Context) string {
	v, err := des.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (des *DictionaryEntrySelect) Ints(ctx context.Context) ([]int, error) {
	if len(des.fields) > 1 {
		return nil, errors.New("ent: DictionaryEntrySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := des.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (des *DictionaryEntrySelect) IntsX(ctx context.Context) []int {
	v, err := des.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (des *DictionaryEntrySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = des.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{dictionaryentry.Label}
	default:
		err = fmt.Errorf("ent: DictionaryEntrySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (des *DictionaryEntrySelect) IntX(ctx context.Context) int {
	v, err := des.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (des *DictionaryEntrySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(des.fields) > 1 {
		return nil, errors.New("ent: DictionaryEntrySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := des.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (des *DictionaryEntrySelect) Float64sX(ctx context.Context) []float64 {
	v, err := des.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (des *DictionaryEntrySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = des.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{dictionaryentry.Label}
	default:
		err = fmt.Errorf("ent: DictionaryEntrySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (des *DictionaryEntrySelect) Float64X(ctx context.Context) float64 {
	v, err := des.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (des *DictionaryEntrySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(des.fields) > 1 {
		return nil, errors.New("ent: DictionaryEntrySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := des.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (des *DictionaryEntrySelect) BoolsX(ctx context.Context) []bool {
	v, err := des.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (des *DictionaryEntrySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = des.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{dictionaryentry.Label}
	default:
		err = fmt.Errorf("ent: DictionaryEntrySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (des *DictionaryEntrySelect) BoolX(ctx context.Context) bool {
	v, err := des.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (des *DictionaryEntrySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := des.sqlQuery().Query()
	if err := des.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (des *DictionaryEntrySelect) sqlQuery() sql.Querier {
	selector := des.sql
	selector.Select(selector.Columns(des.fields...)...)
	return selector
}
