// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/dictionaryentry"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/predicate"
)

// DictionaryEntryDelete is the builder for deleting a DictionaryEntry entity.
type DictionaryEntryDelete struct {
	config
	hooks    []Hook
	mutation *DictionaryEntryMutation
}

// Where adds a new predicate to the DictionaryEntryDelete builder.
func (ded *DictionaryEntryDelete) Where(ps ...predicate.DictionaryEntry) *DictionaryEntryDelete {
	ded.mutation.predicates = append(ded.mutation.predicates, ps...)
	return ded
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ded *DictionaryEntryDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ded.hooks) == 0 {
		affected, err = ded.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DictionaryEntryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ded.mutation = mutation
			affected, err = ded.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ded.hooks) - 1; i >= 0; i-- {
			mut = ded.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ded.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ded *DictionaryEntryDelete) ExecX(ctx context.Context) int {
	n, err := ded.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ded *DictionaryEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: dictionaryentry.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dictionaryentry.FieldID,
			},
		},
	}
	if ps := ded.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ded.driver, _spec)
}

// DictionaryEntryDeleteOne is the builder for deleting a single DictionaryEntry entity.
type DictionaryEntryDeleteOne struct {
	ded *DictionaryEntryDelete
}

// Exec executes the deletion query.
func (dedo *DictionaryEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := dedo.ded.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dictionaryentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dedo *DictionaryEntryDeleteOne) ExecX(ctx context.Context) {
	dedo.ded.ExecX(ctx)
}
