// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/indicatorparams"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/predicate"
)

// IndicatorParamsDelete is the builder for deleting a IndicatorParams entity.
type IndicatorParamsDelete struct {
	config
	hooks    []Hook
	mutation *IndicatorParamsMutation
}

// Where adds a new predicate to the IndicatorParamsDelete builder.
func (ipd *IndicatorParamsDelete) Where(ps ...predicate.IndicatorParams) *IndicatorParamsDelete {
	ipd.mutation.predicates = append(ipd.mutation.predicates, ps...)
	return ipd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ipd *IndicatorParamsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ipd.hooks) == 0 {
		affected, err = ipd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*IndicatorParamsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ipd.mutation = mutation
			affected, err = ipd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ipd.hooks) - 1; i >= 0; i-- {
			mut = ipd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ipd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ipd *IndicatorParamsDelete) ExecX(ctx context.Context) int {
	n, err := ipd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ipd *IndicatorParamsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: indicatorparams.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: indicatorparams.FieldID,
			},
		},
	}
	if ps := ipd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ipd.driver, _spec)
}

// IndicatorParamsDeleteOne is the builder for deleting a single IndicatorParams entity.
type IndicatorParamsDeleteOne struct {
	ipd *IndicatorParamsDelete
}

// Exec executes the deletion query.
func (ipdo *IndicatorParamsDeleteOne) Exec(ctx context.Context) error {
	n, err := ipdo.ipd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{indicatorparams.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ipdo *IndicatorParamsDeleteOne) ExecX(ctx context.Context) {
	ipdo.ipd.ExecX(ctx)
}
