// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/indicator"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/indicatorvaluealias"
)

// IndicatorValueAliasCreate is the builder for creating a IndicatorValueAlias entity.
type IndicatorValueAliasCreate struct {
	config
	mutation *IndicatorValueAliasMutation
	hooks    []Hook
}

// SetValueMapping sets the "value_mapping" field.
func (ivac *IndicatorValueAliasCreate) SetValueMapping(m map[float64]string) *IndicatorValueAliasCreate {
	ivac.mutation.SetValueMapping(m)
	return ivac
}

// SetIndicatorID sets the "indicator" edge to the Indicator entity by ID.
func (ivac *IndicatorValueAliasCreate) SetIndicatorID(id int) *IndicatorValueAliasCreate {
	ivac.mutation.SetIndicatorID(id)
	return ivac
}

// SetIndicator sets the "indicator" edge to the Indicator entity.
func (ivac *IndicatorValueAliasCreate) SetIndicator(i *Indicator) *IndicatorValueAliasCreate {
	return ivac.SetIndicatorID(i.ID)
}

// Mutation returns the IndicatorValueAliasMutation object of the builder.
func (ivac *IndicatorValueAliasCreate) Mutation() *IndicatorValueAliasMutation {
	return ivac.mutation
}

// Save creates the IndicatorValueAlias in the database.
func (ivac *IndicatorValueAliasCreate) Save(ctx context.Context) (*IndicatorValueAlias, error) {
	var (
		err  error
		node *IndicatorValueAlias
	)
	if len(ivac.hooks) == 0 {
		if err = ivac.check(); err != nil {
			return nil, err
		}
		node, err = ivac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*IndicatorValueAliasMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ivac.check(); err != nil {
				return nil, err
			}
			ivac.mutation = mutation
			node, err = ivac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ivac.hooks) - 1; i >= 0; i-- {
			mut = ivac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ivac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ivac *IndicatorValueAliasCreate) SaveX(ctx context.Context) *IndicatorValueAlias {
	v, err := ivac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (ivac *IndicatorValueAliasCreate) check() error {
	if _, ok := ivac.mutation.IndicatorID(); !ok {
		return &ValidationError{Name: "indicator", err: errors.New("ent: missing required edge \"indicator\"")}
	}
	return nil
}

func (ivac *IndicatorValueAliasCreate) sqlSave(ctx context.Context) (*IndicatorValueAlias, error) {
	_node, _spec := ivac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ivac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ivac *IndicatorValueAliasCreate) createSpec() (*IndicatorValueAlias, *sqlgraph.CreateSpec) {
	var (
		_node = &IndicatorValueAlias{config: ivac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: indicatorvaluealias.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: indicatorvaluealias.FieldID,
			},
		}
	)
	if value, ok := ivac.mutation.ValueMapping(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: indicatorvaluealias.FieldValueMapping,
		})
		_node.ValueMapping = value
	}
	if nodes := ivac.mutation.IndicatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   indicatorvaluealias.IndicatorTable,
			Columns: []string{indicatorvaluealias.IndicatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: indicator.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IndicatorValueAliasCreateBulk is the builder for creating many IndicatorValueAlias entities in bulk.
type IndicatorValueAliasCreateBulk struct {
	config
	builders []*IndicatorValueAliasCreate
}

// Save creates the IndicatorValueAlias entities in the database.
func (ivacb *IndicatorValueAliasCreateBulk) Save(ctx context.Context) ([]*IndicatorValueAlias, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ivacb.builders))
	nodes := make([]*IndicatorValueAlias, len(ivacb.builders))
	mutators := make([]Mutator, len(ivacb.builders))
	for i := range ivacb.builders {
		func(i int, root context.Context) {
			builder := ivacb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IndicatorValueAliasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ivacb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ivacb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ivacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ivacb *IndicatorValueAliasCreateBulk) SaveX(ctx context.Context) []*IndicatorValueAlias {
	v, err := ivacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
