// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/indicator"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/scale"
)

// ScaleCreate is the builder for creating a Scale entity.
type ScaleCreate struct {
	config
	mutation *ScaleMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (sc *ScaleCreate) SetType(s string) *ScaleCreate {
	sc.mutation.SetType(s)
	return sc
}

// SetTitle sets the "title" field.
func (sc *ScaleCreate) SetTitle(s string) *ScaleCreate {
	sc.mutation.SetTitle(s)
	return sc
}

// SetDescription sets the "description" field.
func (sc *ScaleCreate) SetDescription(s string) *ScaleCreate {
	sc.mutation.SetDescription(s)
	return sc
}

// AddIndicatorIDs adds the "indicators" edge to the Indicator entity by IDs.
func (sc *ScaleCreate) AddIndicatorIDs(ids ...int) *ScaleCreate {
	sc.mutation.AddIndicatorIDs(ids...)
	return sc
}

// AddIndicators adds the "indicators" edges to the Indicator entity.
func (sc *ScaleCreate) AddIndicators(i ...*Indicator) *ScaleCreate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return sc.AddIndicatorIDs(ids...)
}

// Mutation returns the ScaleMutation object of the builder.
func (sc *ScaleCreate) Mutation() *ScaleMutation {
	return sc.mutation
}

// Save creates the Scale in the database.
func (sc *ScaleCreate) Save(ctx context.Context) (*Scale, error) {
	var (
		err  error
		node *Scale
	)
	if len(sc.hooks) == 0 {
		if err = sc.check(); err != nil {
			return nil, err
		}
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScaleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sc.check(); err != nil {
				return nil, err
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *ScaleCreate) SaveX(ctx context.Context) *Scale {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (sc *ScaleCreate) check() error {
	if _, ok := sc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New("ent: missing required field \"type\"")}
	}
	if v, ok := sc.mutation.GetType(); ok {
		if err := scale.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf("ent: validator failed for field \"type\": %w", err)}
		}
	}
	if _, ok := sc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New("ent: missing required field \"title\"")}
	}
	if v, ok := sc.mutation.Title(); ok {
		if err := scale.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf("ent: validator failed for field \"title\": %w", err)}
		}
	}
	if _, ok := sc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New("ent: missing required field \"description\"")}
	}
	if v, ok := sc.mutation.Description(); ok {
		if err := scale.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf("ent: validator failed for field \"description\": %w", err)}
		}
	}
	return nil
}

func (sc *ScaleCreate) sqlSave(ctx context.Context) (*Scale, error) {
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (sc *ScaleCreate) createSpec() (*Scale, *sqlgraph.CreateSpec) {
	var (
		_node = &Scale{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: scale.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: scale.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: scale.FieldType,
		})
		_node.Type = value
	}
	if value, ok := sc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: scale.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := sc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: scale.FieldDescription,
		})
		_node.Description = value
	}
	if nodes := sc.mutation.IndicatorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scale.IndicatorsTable,
			Columns: []string{scale.IndicatorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: indicator.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScaleCreateBulk is the builder for creating many Scale entities in bulk.
type ScaleCreateBulk struct {
	config
	builders []*ScaleCreate
}

// Save creates the Scale entities in the database.
func (scb *ScaleCreateBulk) Save(ctx context.Context) ([]*Scale, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Scale, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScaleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *ScaleCreateBulk) SaveX(ctx context.Context) []*Scale {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
