# configuration file template
env: dev
db:
  uri: "host=localhost port=5442 user=test dbname=correlateme password=pass sslmode=disable"
  driver: postgres
server:
  port: 8000
  host: "0.0.0.0"
auth:
  exp: 7200 # hours
  secret: secret-key
app:
  defaultObservationLimit: 200
  maxCorrelationObservations: 500
  minCorrelationObservations: 10
