# configuration file example
env: dev
db:
  uri: "host=localhost port=5442 user=test dbname=correlateme password=pass sslmode=disable"
  driver: postgres
server:
  port: 8000
  host: "0.0.0.0"
auth:
  exp: 7200 # hours
  secret: secret-key
app:
  defaultObservationLimit: 200
  maxCorrelationObservations: 500
  minCorrelationObservations: 10
  updateCorrelationsBuffer: 1000
  updateAggregationsBuffer: 1000
  maxWeekAggregationObservations: 1400
  maxMonthAggregationObservations: 3000
job:
  gatherAndSendServiceStatsSchedule: "0 0 0 1 ?"
external:
  telegram:
    telegramTo: 1999 # chat id
    telegramToken: "tg-token"
data:
  presets:
    scalePresetsPath: "./data/presets/scales.json"
    indicatorPresetsPath: "./data/presets/indicators.json"
    dictionaryPresetsPath: "./data/presets/dictionaries.json"
    dictionaryEntryPresetsPath: "./data/presets/dictionary_entries.json"