# configuration file template
env: dev
db:
  uri: "host=localhost port=5442 user=test dbname=detector password=pass sslmode=disable"
  driver: postgres
server:
  port: 8000
  host: "0.0.0.0"
notification:
  approveOnSend: false
  schedule: "*/10 * * * *"
auth:
  exp: 7200 # hours
  secret: secret-key