env: dev
db:
  uri: "host={{db_host}} port={{db_port}} user={{db_user}} dbname={{db_name}} password={{db_password}} sslmode=disable"
  driver: postgres
server:
  port: 8000
  host: "0.0.0.0"
auth:
  exp: 7200 # hours
  secret: {{secret_key}}
app:
  defaultObservationLimit: 200
  maxCorrelationObservations: 500
  minCorrelationObservations: 10
  updateCorrelationsBuffer: 1000
  updateAggregationsBuffer: 1000
  maxWeekAggregationObservations: 1400
  maxMonthAggregationObservations: 3000
