// Code generated by entc, DO NOT EDIT.

package correlation

import (
	"time"
)

const (
	// Label holds the string label denoting the correlation type in the database.
	Label = "correlation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldCoef holds the string denoting the coef field in the database.
	FieldCoef = "coef"
	// FieldP holds the string denoting the p field in the database.
	FieldP = "p"
	// FieldR2 holds the string denoting the r2 field in the database.
	FieldR2 = "r2"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"

	// EdgeLeft holds the string denoting the left edge name in mutations.
	EdgeLeft = "left"
	// EdgeRight holds the string denoting the right edge name in mutations.
	EdgeRight = "right"

	// Table holds the table name of the correlation in the database.
	Table = "correlations"
	// LeftTable is the table the holds the left relation/edge.
	LeftTable = "correlations"
	// LeftInverseTable is the table name for the Dataset entity.
	// It exists in this package in order to avoid circular dependency with the "dataset" package.
	LeftInverseTable = "datasets"
	// LeftColumn is the table column denoting the left relation/edge.
	LeftColumn = "dataset_left"
	// RightTable is the table the holds the right relation/edge.
	RightTable = "correlations"
	// RightInverseTable is the table name for the Dataset entity.
	// It exists in this package in order to avoid circular dependency with the "dataset" package.
	RightInverseTable = "datasets"
	// RightColumn is the table column denoting the right relation/edge.
	RightColumn = "dataset_right"
)

// Columns holds all SQL columns for correlation fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldCoef,
	FieldP,
	FieldR2,
	FieldType,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Correlation type.
var ForeignKeys = []string{
	"dataset_left",
	"dataset_right",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
)
