// Code generated by entc, DO NOT EDIT.

package indicatorparams

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/DanielTitkov/correlateme-server/internal/repository/entgo/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// ValueMappingIsNil applies the IsNil predicate on the "value_mapping" field.
func ValueMappingIsNil() predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldValueMapping)))
	})
}

// ValueMappingNotNil applies the NotNil predicate on the "value_mapping" field.
func ValueMappingNotNil() predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldValueMapping)))
	})
}

// HasIndicator applies the HasEdge predicate on the "indicator" edge.
func HasIndicator() predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IndicatorTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, IndicatorTable, IndicatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIndicatorWith applies the HasEdge predicate on the "indicator" edge with a given conditions (other predicates).
func HasIndicatorWith(preds ...predicate.Indicator) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IndicatorInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, IndicatorTable, IndicatorColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IndicatorParams) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IndicatorParams) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IndicatorParams) predicate.IndicatorParams {
	return predicate.IndicatorParams(func(s *sql.Selector) {
		p(s.Not())
	})
}
